<?php

namespace Container6yt2OX8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WUx6rrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WUx_6rr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WUx_6rr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'gpt' => ['privates', 'App\\Repository\\GroupeTagRepository', 'getGroupeTagRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'tagRepository' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'gpt' => 'App\\Repository\\GroupeTagRepository',
            'serializer' => '?',
            'tagRepository' => 'App\\Repository\\TagRepository',
        ]);
    }
}
