<?php

namespace ContainerMgq3OXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fw7pQz3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fw7pQz3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fw7pQz3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cmp' => ['privates', '.errored..service_locator.Fw7pQz3.App\\Repository\\GroupecompetenceRepository', NULL, 'Cannot autowire service ".service_locator.Fw7pQz3": it references class "App\\Repository\\GroupecompetenceRepository" but no such service exists. Did you mean "App\\Repository\\GroupeCompetenceRepository"?'],
            'grpcmp' => ['privates', 'App\\Repository\\ReferentielRepository', 'getReferentielRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'validator' => ['services', 'validator', 'getValidatorService', false],
        ], [
            'cmp' => 'App\\Repository\\GroupecompetenceRepository',
            'grpcmp' => 'App\\Repository\\ReferentielRepository',
            'manager' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
