<?php

namespace ContainerMgq3OXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupecompetenceRepository2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bk_JP9I.App\Repository\GroupecompetenceRepository' shared service.
     *
     * @return \App\Repository\GroupecompetenceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.bk_JP9I": it references class "App\\Repository\\GroupecompetenceRepository" but no such service exists. Did you mean "App\\Repository\\GroupeCompetenceRepository"?');
    }
}
