<?php

namespace ContainerFDad7sr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8tZtKnzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8tZtKnz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8tZtKnz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::addAdmin' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\AdminController::updateAdmin' => ['privates', '.service_locator.wa_PTUC', 'get_ServiceLocator_WaPTUCService', true],
            'App\\Controller\\ApprenantController::addApprenant' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\CMController::addCM' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\CMController::updateCm' => ['privates', '.service_locator.tQCFC.H', 'get_ServiceLocator_TQCFC_HService', true],
            'App\\Controller\\FormateurController::addFormateur' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\FormateurController::updateFormateur' => ['privates', '.service_locator.FidDLBm', 'get_ServiceLocator_FidDLBmService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AdminController:addAdmin' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\AdminController:updateAdmin' => ['privates', '.service_locator.wa_PTUC', 'get_ServiceLocator_WaPTUCService', true],
            'App\\Controller\\ApprenantController:addApprenant' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\CMController:addCM' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\CMController:updateCm' => ['privates', '.service_locator.tQCFC.H', 'get_ServiceLocator_TQCFC_HService', true],
            'App\\Controller\\FormateurController:addFormateur' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\FormateurController:updateFormateur' => ['privates', '.service_locator.FidDLBm', 'get_ServiceLocator_FidDLBmService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AdminController::addAdmin' => '?',
            'App\\Controller\\AdminController::updateAdmin' => '?',
            'App\\Controller\\ApprenantController::addApprenant' => '?',
            'App\\Controller\\CMController::addCM' => '?',
            'App\\Controller\\CMController::updateCm' => '?',
            'App\\Controller\\FormateurController::addFormateur' => '?',
            'App\\Controller\\FormateurController::updateFormateur' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:addAdmin' => '?',
            'App\\Controller\\AdminController:updateAdmin' => '?',
            'App\\Controller\\ApprenantController:addApprenant' => '?',
            'App\\Controller\\CMController:addCM' => '?',
            'App\\Controller\\CMController:updateCm' => '?',
            'App\\Controller\\FormateurController:addFormateur' => '?',
            'App\\Controller\\FormateurController:updateFormateur' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
