<?php

namespace ContainerDdSe0vT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lb3OZhVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lb3OZhV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lb3OZhV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'gpt' => ['privates', 'App\\Repository\\GroupeTagRepository', 'getGroupeTagRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'tagRepository' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'gpt' => 'App\\Repository\\GroupeTagRepository',
            'manager' => '?',
            'serializer' => '?',
            'tagRepository' => 'App\\Repository\\TagRepository',
        ]);
    }
}
