<?php

namespace ContainerDdSe0vT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YmR6qs4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YmR6qs4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YmR6qs4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailService' => ['privates', 'App\\service\\MailService', 'getMailServiceService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'upService' => ['privates', 'App\\service\\UserService', 'getUserServiceService', true],
        ], [
            'mailService' => 'App\\service\\MailService',
            'manager' => '?',
            'upService' => 'App\\service\\UserService',
        ]);
    }
}
