<?php

namespace ContainerWaqcHdV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Is20aNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Is_20aN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Is_20aN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::addAdmin' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\ApprenantController::addApprenant' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\CMController::addCM' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\FormateurController::addFormateur' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\FormateurController::updateFormateur' => ['privates', '.service_locator.FidDLBm', 'get_ServiceLocator_FidDLBmService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AdminController:addAdmin' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\ApprenantController:addApprenant' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\CMController:addCM' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\FormateurController:addFormateur' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\FormateurController:updateFormateur' => ['privates', '.service_locator.FidDLBm', 'get_ServiceLocator_FidDLBmService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AdminController::addAdmin' => '?',
            'App\\Controller\\ApprenantController::addApprenant' => '?',
            'App\\Controller\\CMController::addCM' => '?',
            'App\\Controller\\FormateurController::addFormateur' => '?',
            'App\\Controller\\FormateurController::updateFormateur' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:addAdmin' => '?',
            'App\\Controller\\ApprenantController:addApprenant' => '?',
            'App\\Controller\\CMController:addCM' => '?',
            'App\\Controller\\FormateurController:addFormateur' => '?',
            'App\\Controller\\FormateurController:updateFormateur' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
