<?php

namespace ContainerPUDMlCQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WaPTUCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wa_PTUC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wa_PTUC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ADMINRepository' => ['privates', 'App\\Repository\\ADMINRepository', 'getADMINRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'update' => ['privates', 'App\\service\\UserService', 'getUserServiceService', true],
        ], [
            'ADMINRepository' => 'App\\Repository\\ADMINRepository',
            'manager' => '?',
            'update' => 'App\\service\\UserService',
        ]);
    }
}
