<?php

namespace ContainerXzJR6D9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Csxx3ZxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.csxx3Zx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.csxx3Zx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::addAdmin' => ['privates', '.service_locator.YmR6qs4', 'get_ServiceLocator_YmR6qs4Service', true],
            'App\\Controller\\AdminController::updateAdmin' => ['privates', '.service_locator.wa_PTUC', 'get_ServiceLocator_WaPTUCService', true],
            'App\\Controller\\ApprenantController::addApprenant' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\CMController::addCM' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\CMController::updateCm' => ['privates', '.service_locator.tQCFC.H', 'get_ServiceLocator_TQCFC_HService', true],
            'App\\Controller\\CompetenceController::addCompetence' => ['privates', '.service_locator.hall1zc', 'get_ServiceLocator_Hall1zcService', true],
            'App\\Controller\\CompetenceController::showCompetence' => ['privates', '.service_locator.EFPYbVF', 'get_ServiceLocator_EFPYbVFService', true],
            'App\\Controller\\CompetenceController::updateCompetence' => ['privates', '.service_locator.ihUGo0D', 'get_ServiceLocator_IhUGo0DService', true],
            'App\\Controller\\FormateurController::addFormateur' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\FormateurController::updateFormateur' => ['privates', '.service_locator.FidDLBm', 'get_ServiceLocator_FidDLBmService', true],
            'App\\Controller\\GroupeCompetenceController::addGroupecompetence' => ['privates', '.service_locator.19ps0qC', 'get_ServiceLocator_19ps0qCService', true],
            'App\\Controller\\GroupeCompetenceController::showGroupecompetence' => ['privates', '.service_locator.hPoglkx', 'get_ServiceLocator_HPoglkxService', true],
            'App\\Controller\\GroupeCompetenceController::updateGroupecompetence' => ['privates', '.service_locator.fdjmwBO', 'get_ServiceLocator_FdjmwBOService', true],
            'App\\Controller\\GroupetagController::addGroupetag' => ['privates', '.service_locator.19ps0qC', 'get_ServiceLocator_19ps0qCService', true],
            'App\\Controller\\GroupetagController::updateGroupetag' => ['privates', '.service_locator.lb3OZhV', 'get_ServiceLocator_Lb3OZhVService', true],
            'App\\Controller\\ReferentielController::addReferentiel' => ['privates', '.service_locator.toGFvjt', 'get_ServiceLocator_ToGFvjtService', true],
            'App\\Controller\\ReferentielController::showReferentiel' => ['privates', '.service_locator.M3HL8pi', 'get_ServiceLocator_M3HL8piService', true],
            'App\\Controller\\ReferentielController::updateReferentiel' => ['privates', '.service_locator.cjnRAGz', 'get_ServiceLocator_CjnRAGzService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AdminController:addAdmin' => ['privates', '.service_locator.YmR6qs4', 'get_ServiceLocator_YmR6qs4Service', true],
            'App\\Controller\\AdminController:updateAdmin' => ['privates', '.service_locator.wa_PTUC', 'get_ServiceLocator_WaPTUCService', true],
            'App\\Controller\\ApprenantController:addApprenant' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\CMController:addCM' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\CMController:updateCm' => ['privates', '.service_locator.tQCFC.H', 'get_ServiceLocator_TQCFC_HService', true],
            'App\\Controller\\CompetenceController:addCompetence' => ['privates', '.service_locator.hall1zc', 'get_ServiceLocator_Hall1zcService', true],
            'App\\Controller\\CompetenceController:showCompetence' => ['privates', '.service_locator.EFPYbVF', 'get_ServiceLocator_EFPYbVFService', true],
            'App\\Controller\\CompetenceController:updateCompetence' => ['privates', '.service_locator.ihUGo0D', 'get_ServiceLocator_IhUGo0DService', true],
            'App\\Controller\\FormateurController:addFormateur' => ['privates', '.service_locator.laWtL56', 'get_ServiceLocator_LaWtL56Service', true],
            'App\\Controller\\FormateurController:updateFormateur' => ['privates', '.service_locator.FidDLBm', 'get_ServiceLocator_FidDLBmService', true],
            'App\\Controller\\GroupeCompetenceController:addGroupecompetence' => ['privates', '.service_locator.19ps0qC', 'get_ServiceLocator_19ps0qCService', true],
            'App\\Controller\\GroupeCompetenceController:showGroupecompetence' => ['privates', '.service_locator.hPoglkx', 'get_ServiceLocator_HPoglkxService', true],
            'App\\Controller\\GroupeCompetenceController:updateGroupecompetence' => ['privates', '.service_locator.fdjmwBO', 'get_ServiceLocator_FdjmwBOService', true],
            'App\\Controller\\GroupetagController:addGroupetag' => ['privates', '.service_locator.19ps0qC', 'get_ServiceLocator_19ps0qCService', true],
            'App\\Controller\\GroupetagController:updateGroupetag' => ['privates', '.service_locator.lb3OZhV', 'get_ServiceLocator_Lb3OZhVService', true],
            'App\\Controller\\ReferentielController:addReferentiel' => ['privates', '.service_locator.toGFvjt', 'get_ServiceLocator_ToGFvjtService', true],
            'App\\Controller\\ReferentielController:showReferentiel' => ['privates', '.service_locator.M3HL8pi', 'get_ServiceLocator_M3HL8piService', true],
            'App\\Controller\\ReferentielController:updateReferentiel' => ['privates', '.service_locator.cjnRAGz', 'get_ServiceLocator_CjnRAGzService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AdminController::addAdmin' => '?',
            'App\\Controller\\AdminController::updateAdmin' => '?',
            'App\\Controller\\ApprenantController::addApprenant' => '?',
            'App\\Controller\\CMController::addCM' => '?',
            'App\\Controller\\CMController::updateCm' => '?',
            'App\\Controller\\CompetenceController::addCompetence' => '?',
            'App\\Controller\\CompetenceController::showCompetence' => '?',
            'App\\Controller\\CompetenceController::updateCompetence' => '?',
            'App\\Controller\\FormateurController::addFormateur' => '?',
            'App\\Controller\\FormateurController::updateFormateur' => '?',
            'App\\Controller\\GroupeCompetenceController::addGroupecompetence' => '?',
            'App\\Controller\\GroupeCompetenceController::showGroupecompetence' => '?',
            'App\\Controller\\GroupeCompetenceController::updateGroupecompetence' => '?',
            'App\\Controller\\GroupetagController::addGroupetag' => '?',
            'App\\Controller\\GroupetagController::updateGroupetag' => '?',
            'App\\Controller\\ReferentielController::addReferentiel' => '?',
            'App\\Controller\\ReferentielController::showReferentiel' => '?',
            'App\\Controller\\ReferentielController::updateReferentiel' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:addAdmin' => '?',
            'App\\Controller\\AdminController:updateAdmin' => '?',
            'App\\Controller\\ApprenantController:addApprenant' => '?',
            'App\\Controller\\CMController:addCM' => '?',
            'App\\Controller\\CMController:updateCm' => '?',
            'App\\Controller\\CompetenceController:addCompetence' => '?',
            'App\\Controller\\CompetenceController:showCompetence' => '?',
            'App\\Controller\\CompetenceController:updateCompetence' => '?',
            'App\\Controller\\FormateurController:addFormateur' => '?',
            'App\\Controller\\FormateurController:updateFormateur' => '?',
            'App\\Controller\\GroupeCompetenceController:addGroupecompetence' => '?',
            'App\\Controller\\GroupeCompetenceController:showGroupecompetence' => '?',
            'App\\Controller\\GroupeCompetenceController:updateGroupecompetence' => '?',
            'App\\Controller\\GroupetagController:addGroupetag' => '?',
            'App\\Controller\\GroupetagController:updateGroupetag' => '?',
            'App\\Controller\\ReferentielController:addReferentiel' => '?',
            'App\\Controller\\ReferentielController:showReferentiel' => '?',
            'App\\Controller\\ReferentielController:updateReferentiel' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
