<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'DoctrineNamespaceCacheKey%5B%5D' => 0,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23setContainer%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23setContainer%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getParameter%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getParameter%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getSubscribedServices%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getSubscribedServices%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23has%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23has%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23get%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23get%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23generateUrl%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23generateUrl%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23forward%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23forward%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirect%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirect%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirectToRoute%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23redirectToRoute%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23json%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23json%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23file%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23file%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addFlash%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addFlash%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isGranted%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isGranted%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23denyAccessUnlessGranted%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23denyAccessUnlessGranted%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23renderView%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23renderView%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23render%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23render%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23stream%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23stream%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createNotFoundException%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createNotFoundException%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createAccessDeniedException%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createAccessDeniedException%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createForm%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createForm%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createFormBuilder%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23createFormBuilder%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getDoctrine%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getDoctrine%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getUser%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23getUser%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isCsrfTokenValid%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23isCsrfTokenValid%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23dispatchMessage%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23dispatchMessage%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addLink%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%23addLink%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%24container%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CAbstractController%24container%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CADMIN%5D%5B1%5D' => 3,
'%5B%5BC%5DApp%5CEntity%5CADMIN%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CADMIN%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CADMIN%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getUsername%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getUsername%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setUsername%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setUsername%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getRoles%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getRoles%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setRoles%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setRoles%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getPassword%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getPassword%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setPassword%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setPassword%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getSalt%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getSalt%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23eraseCredentials%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23eraseCredentials%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getNom%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getNom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setNom%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setNom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getPrenom%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getPrenom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setPrenom%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setPrenom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getEmail%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getEmail%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setEmail%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setEmail%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getStatut%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getStatut%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setStatut%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setStatut%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getAvatar%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getAvatar%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setAvatar%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setAvatar%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getProfil%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getProfil%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setProfil%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setProfil%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getArchivage%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getArchivage%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23setArchivage%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23setArchivage%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CADMIN%24id%5D%5B1%5D' => 4,
'%5B%5BC%5DApp%5CEntity%5CADMIN%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24username%5D%5B1%5D' => 5,
'%5B%5BC%5DApp%5CEntity%5CUser%24username%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24roles%5D%5B1%5D' => 6,
'%5B%5BC%5DApp%5CEntity%5CUser%24roles%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24password%5D%5B1%5D' => 7,
'%5B%5BC%5DApp%5CEntity%5CUser%24password%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24Nom%5D%5B1%5D' => 8,
'%5B%5BC%5DApp%5CEntity%5CUser%24Nom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24Prenom%5D%5B1%5D' => 8,
'%5B%5BC%5DApp%5CEntity%5CUser%24Prenom%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24Email%5D%5B1%5D' => 8,
'%5B%5BC%5DApp%5CEntity%5CUser%24Email%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24Statut%5D%5B1%5D' => 8,
'%5B%5BC%5DApp%5CEntity%5CUser%24Statut%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24Avatar%5D%5B1%5D' => 9,
'%5B%5BC%5DApp%5CEntity%5CUser%24Avatar%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%5D%5B1%5D' => 10,
'%5B%5BC%5DApp%5CEntity%5CApprenant%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CApprenant%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CApprenant%24id%5D%5B1%5D' => 4,
'%5B%5BC%5DApp%5CEntity%5CApprenant%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CCM%5D%5B1%5D' => 11,
'%5B%5BC%5DApp%5CEntity%5CCM%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CCM%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CCM%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CCM%24id%5D%5B1%5D' => 4,
'%5B%5BC%5DApp%5CEntity%5CCM%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CFormateur%5D%5B1%5D' => 12,
'%5B%5BC%5DApp%5CEntity%5CFormateur%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CFormateur%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CFormateur%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CFormateur%24id%5D%5B1%5D' => 4,
'%5B%5BC%5DApp%5CEntity%5CFormateur%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%5D%5B1%5D' => 13,
'%5B%5BC%5DApp%5CEntity%5CProfil%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23__construct%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23getLibelle%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23getLibelle%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23setLibelle%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23setLibelle%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23getUsers%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23getUsers%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23addUser%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23addUser%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23removeUser%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23removeUser%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23getStatut%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23getStatut%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%23setStatut%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CProfil%23setStatut%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%24id%5D%5B1%5D' => 14,
'%5B%5BC%5DApp%5CEntity%5CProfil%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%24Libelle%5D%5B1%5D' => 15,
'%5B%5BC%5DApp%5CEntity%5CProfil%24Libelle%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%24users%5D%5B1%5D' => 16,
'%5B%5BC%5DApp%5CEntity%5CProfil%24users%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CProfil%24Statut%5D%5B1%5D' => 17,
'%5B%5BC%5DApp%5CEntity%5CProfil%24Statut%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%5D%5B1%5D' => 18,
'%5B%5BC%5DApp%5CEntity%5CUser%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%23getId%5D%5B1%5D' => 1,
'%5B%5BC%5DApp%5CEntity%5CUser%23getId%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24id%5D%5B1%5D' => 19,
'%5B%5BC%5DApp%5CEntity%5CUser%24id%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24profil%5D%5B1%5D' => 20,
'%5B%5BC%5DApp%5CEntity%5CUser%24profil%5D%5B1%5D' => 2,
'%5BApp%5CEntity%5CUser%24Archivage%5D%5B1%5D' => 21,
'%5B%5BC%5DApp%5CEntity%5CUser%24Archivage%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23setContainer%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23setContainer%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainAction%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainAction%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLitePlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLitePlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLServerPlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainSQLServerPlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOtherPlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOtherPlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOraclePlatform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%23explainOraclePlatform%5D%5B1%5D' => 2,
'%5BDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%24container%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CBundle%5CDoctrineBundle%5CController%5CProfilerController%24container%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23addInsert%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23addInsert%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInsertSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getInsertSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getResultSetMapping%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getResultSetMapping%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23exists%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23exists%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCacheRegion%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getCacheRegion%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getEntityHydrator%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getEntityHydrator%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeEntityCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeEntityCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeJoinedAssociations%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23storeJoinedAssociations%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getHash%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getHash%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23load%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23load%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadAll%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadAll%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadById%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadById%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23count%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23count%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadCriteria%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadCriteria%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23lock%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23lock%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23refresh%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23refresh%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23buildCollectionCacheKey%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%23buildCollectionCacheKey%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionComplete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionComplete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionRolledBack%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23afterTransactionRolledBack%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24uow%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24uow%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24metadataFactory%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24metadataFactory%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24persister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24persister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24class%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24class%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24queuedCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24queuedCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24region%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24region%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampRegion%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampRegion%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampKey%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24timestampKey%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24hydrator%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24hydrator%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cacheLogger%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24cacheLogger%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24regionName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24regionName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24joinedAssociations%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CAbstractEntityPersister%24joinedAssociations%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23getEntityHydrator%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23getEntityHydrator%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23storeEntityCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CCachedEntityPersister%23storeEntityCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23getCacheRegion%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CCachedPersister%23getCacheRegion%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getResultSetMapping%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getResultSetMapping%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInsertSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getInsertSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23addInsert%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23addInsert%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23count%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23count%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23load%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23load%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadById%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadById%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23refresh%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23refresh%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadCriteria%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadCriteria%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadAll%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadAll%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23lock%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23lock%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23exists%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%23exists%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23updateCache%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CNonStrictReadWriteCachedEntityPersister%23updateCache%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadOnlyCachedEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionComplete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23afterTransactionRolledBack%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CCache%5CPersister%5CEntity%5CReadWriteCachedEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23prepareInsertData%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23prepareInsertData%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectJoinColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CAbstractEntityInheritancePersister%23getSelectJoinColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getResultSetMapping%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getResultSetMapping%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23addInsert%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23addInsert%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23assignDefaultVersionValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23assignDefaultVersionValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23fetchVersionValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23fetchVersionValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23extractIdentifierTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23extractIdentifierTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23updateTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23updateTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23deleteJoinTableRecords%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23deleteJoinTableRecords%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareUpdateData%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareUpdateData%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23load%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23load%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadById%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadById%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToOneEntity%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23refresh%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23refresh%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23count%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23count%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCriteria%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCriteria%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandCriteriaParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadAll%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadAll%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadArrayFromStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadArrayFromStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCollectionFromStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadCollectionFromStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadManyToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getManyToManyStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOrderBySQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOrderBySQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnsSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnsSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnAssociationSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnAssociationSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectManyToManyJoinSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectManyToManyJoinSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertColumnList%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getInsertColumnList%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLTableAlias%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLTableAlias%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23lock%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23lock%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getLockTablesSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getLockTablesSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionStatementColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectConditionSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23loadOneToManyCollection%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyStatement%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getOneToManyStatement%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandToManyParameters%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23expandToManyParameters%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getValues%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getValues%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getIndividualValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getIndividualValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23exists%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23exists%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getJoinSQLForJoinColumns%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getJoinSQLForJoinColumns%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLColumnAlias%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSQLColumnAlias%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23generateFilterConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23generateFilterConditionSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23switchPersisterContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23switchPersisterContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassIdentifiersTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getClassIdentifiersTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24class%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24class%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24conn%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24conn%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24platform%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24platform%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24em%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24em%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24queuedInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24queuedInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24columnTypes%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24columnTypes%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quotedColumns%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quotedColumns%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quoteStrategy%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24quoteStrategy%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24currentPersisterContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24currentPersisterContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareInsertData%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23prepareInsertData%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%23getSelectColumnSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24comparisonMap%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24comparisonMap%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24insertSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24insertSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24identifierFlattener%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24identifierFlattener%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24limitsHandlingContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24limitsHandlingContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24noLimitsContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CBasicEntityPersister%24noLimitsContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%23__construct%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24class%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24class%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24rsm%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24rsm%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectColumnListSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectColumnListSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectJoinSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24selectJoinSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlAliasCounter%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlAliasCounter%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlTableAliases%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24sqlTableAliases%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24handlesLimits%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CCachedPersisterContext%24handlesLimits%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CEntityPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getVersionedClassMetadata%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getVersionedClassMetadata%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getOwningTable%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getOwningTable%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23executeInserts%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23executeInserts%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23update%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23update%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23delete%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23delete%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getCountSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getCountSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getLockTablesSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getLockTablesSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectColumnsSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getSelectColumnsSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getInsertColumnList%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getInsertColumnList%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23assignDefaultVersionValue%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23assignDefaultVersionValue%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getJoinSql%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%23getJoinSql%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24owningTableMap%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24owningTableMap%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24quotedTableMap%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CJoinedSubclassPersister%24quotedTableMap%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getDiscriminatorColumnTableName%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectColumnsSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectColumnsSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getInsertColumnList%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getInsertColumnList%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSQLTableAlias%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSQLTableAlias%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionCriteriaSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionDiscriminatorValueSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23getSelectConditionDiscriminatorValueSQL%5D%5B1%5D' => 2,
'%5BDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23generateFilterConditionSQL%5D%5B1%5D' => 1,
'%5B%5BC%5DDoctrine%5CORM%5CPersisters%5CEntity%5CSingleTablePersister%23generateFilterConditionSQL%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__construct%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23redirectAction%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23redirectAction%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23urlRedirectAction%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23urlRedirectAction%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__invoke%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23__invoke%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23parseQuery%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%23parseQuery%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24router%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24router%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpPort%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpPort%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpsPort%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CRedirectController%24httpsPort%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__construct%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23templateAction%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23templateAction%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__invoke%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%23__invoke%5D%5B1%5D' => 2,
'%5BSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%24twig%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CBundle%5CFrameworkBundle%5CController%5CTemplateController%24twig%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23__construct%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23__construct%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23supports%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23supports%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23resolve%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%23resolve%5D%5B1%5D' => 2,
'%5BSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%24tokenStorage%5D%5B1%5D' => 1,
'%5B%5BC%5DSymfony%5CComponent%5CSecurity%5CHttp%5CController%5CUserValueResolver%24tokenStorage%5D%5B1%5D' => 2,

], [

0 => 'N;',
1 => [],
2 => 1606228980,
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
            clone ($p['Doctrine\\ORM\\Mapping\\Table'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Table')),
            clone ($p['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
        ],
        null,
        [
            'stdClass' => [
                'repositoryClass' => [
                    'App\\Repository\\ADMINRepository',
                ],
                'name' => [
                    1 => '`admin`',
                ],
                'collectionOperations' => [
                    2 => [
                        'add_apprenant' => [
                            'method' => 'POST',
                            'path' => '/admin/admins',
                            'security' => 'is_granted(\'ROLE_ADMIN\') or is_granted(\'ROLE_CM\')',
                            'security_message' => 'Vous n\'avez pas access à cette Ressource',
                        ],
                        'get' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas acces a cette ressource.',
                            'path' => 'admin/admins',
                        ],
                        'get_apprenants' => [
                            'method' => 'GET',
                            'path' => '/admins',
                            'security' => '(is_granted(\'ROLE_ADMIN\'))',
                            'security_message' => 'Vous n\'avez pas acces a cette ressource.',
                        ],
                    ],
                ],
                'itemOperations' => [
                    2 => [
                        'get' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/admins/{id}',
                            'defaults' => [
                                'id' => null,
                            ],
                        ],
                        'get_apprenant' => [
                            'method' => 'GET',
                            'path' => '/admins/{id}',
                            'requirements' => [
                                'id' => '\\d+',
                            ],
                            'security' => '(is_granted(\'ROLE_FORMATEUR\'))',
                            'security_message' => 'Vous n\'avez pas access à cette Ressource',
                        ],
                        'delete' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/admins/{id}',
                        ],
                        'patch' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/admins/{id}',
                        ],
                        'put' => [
                            'security_post_denormalize' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/admins/{id}',
                        ],
                    ],
                ],
                'attributes' => [
                    2 => [
                        'security' => 'is_granted(\'ROLE_ADMIN\')',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
        ],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Id'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Id')),
            clone ($p['Doctrine\\ORM\\Mapping\\GeneratedValue'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\GeneratedValue')),
            clone ($p['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    2 => 'integer',
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
        ],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'length' => [
                    180,
                ],
                'unique' => [
                    true,
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    1 => [
                        'user_read',
                        'profil_read',
                        'formateur_read',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'json',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [],
        [
            $o[0],
        ],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'length' => [
                    255,
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    1 => [
                        'user_read',
                        'profil_read',
                        'formateur_read',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'blob',
                ],
                'nullable' => [
                    true,
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
            clone ($p['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
        ],
        null,
        [
            'stdClass' => [
                'repositoryClass' => [
                    'App\\Repository\\ApprenantRepository',
                ],
                'collectionOperations' => [
                    1 => [
                        'post' => [
                            'path' => '/admin/apprenants',
                            'security' => 'is_granted(\'ROLE_ADMIN\') or is_granted(\'ROLE_CM\')',
                            'security_message' => 'Vous n\'avez pas access à cette Ressource',
                        ],
                        'get' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas acces a cette ressource.',
                            'path' => 'admin/apprenants',
                            'normalization_context' => [
                                'groups' => [
                                    'apprenant_read',
                                ],
                            ],
                        ],
                        'get_apprenants' => [
                            'method' => 'GET',
                            'path' => '/apprenants',
                            'security' => '(is_granted(\'ROLE_ADMIN\'))',
                            'security_message' => 'Vous n\'avez pas acces a cette ressource.',
                        ],
                    ],
                ],
                'itemOperations' => [
                    1 => [
                        'get' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/apprenants/{id}',
                            'defaults' => [
                                'id' => null,
                            ],
                        ],
                        'get_apprenant' => [
                            'method' => 'GET',
                            'path' => '/apprenants/{id}',
                            'requirements' => [
                                'id' => '\\d+',
                            ],
                            'security' => '(is_granted(\'ROLE_FORMATEUR\'))',
                            'security_message' => 'Vous n\'avez pas access à cette Ressource',
                        ],
                        'delete' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/apprenants/{id}',
                        ],
                        'patch' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/apprenants/{id}',
                        ],
                        'put' => [
                            'security_post_denormalize' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/apprenants/{id}',
                        ],
                    ],
                ],
                'attributes' => [
                    1 => [
                        'security' => 'is_granted(\'ROLE_ADMIN\')',
                        'normalization_context' => [
                            'groups' => [
                                'apprenant_read',
                                'apprenant_details_read',
                            ],
                        ],
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
            clone ($p['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
        ],
        null,
        [
            'stdClass' => [
                'repositoryClass' => [
                    'App\\Repository\\CMRepository',
                ],
                'collectionOperations' => [
                    1 => [
                        'add_formateur' => [
                            'method' => 'POST',
                            'path' => '/admin/cms',
                            'security' => 'is_granted(\'ROLE_ADMIN\'))',
                            'security_message' => 'Vous n\'avez pas access à cette Ressource',
                        ],
                        'get' => [
                            'path' => '/admin/cms',
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas acces a cette ressource.',
                            'normalization_context' => [
                                'groups' => [
                                    'formateur_read',
                                ],
                            ],
                        ],
                    ],
                ],
                'itemOperations' => [
                    1 => [
                        'get' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/cms/{id}',
                            'defaults' => [
                                'id' => null,
                            ],
                        ],
                        'get_formateur' => [
                            'method' => 'GET',
                            'path' => '/cms/{id}',
                            'requirements' => [
                                'id' => '\\d+',
                            ],
                            'security' => '(is_granted(\'ROLE_FORMATEUR\'))',
                            'security_message' => 'Vous n\'avez pas access à cette Ressource',
                        ],
                        'delete' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/cms/{id}',
                        ],
                        'patch' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/cms/{id}',
                        ],
                        'put' => [
                            'path' => 'admin/cms/{id}',
                            'security_post_denormalize' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                        ],
                    ],
                ],
                'attributes' => [
                    1 => [
                        'security' => 'is_granted(\'ROLE_ADMIN\')',
                        'normalization_context' => [
                            'groups' => [
                                'cm_read',
                                'cm_details_read',
                            ],
                        ],
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
12 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
            clone ($p['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
        ],
        null,
        [
            'stdClass' => [
                'repositoryClass' => [
                    'App\\Repository\\FormateurRepository',
                ],
                'collectionOperations' => [
                    1 => [
                        'add_formateur' => [
                            'method' => 'POST',
                            'path' => '/admin/formateurs',
                            'security' => 'is_granted(\'ROLE_ADMIN\'))',
                            'security_message' => 'Vous n\'avez pas access à cette Ressource',
                        ],
                        'get' => [
                            'path' => '/admin/formateurs',
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas acces a cette ressource.',
                            'normalization_context' => [
                                'groups' => [
                                    'formateur_read',
                                ],
                            ],
                        ],
                    ],
                ],
                'itemOperations' => [
                    1 => [
                        'get' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/formateurs/{id}',
                            'defaults' => [
                                'id' => null,
                            ],
                        ],
                        'get_formateur' => [
                            'method' => 'GET',
                            'path' => '/formateurs/{id}',
                            'requirements' => [
                                'id' => '\\d+',
                            ],
                            'security' => '(is_granted(\'ROLE_FORMATEUR\'))',
                            'security_message' => 'Vous n\'avez pas access à cette Ressource',
                        ],
                        'delete' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/formateurs/{id}',
                        ],
                        'patch' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/formateurs/{id}',
                        ],
                        'put' => [
                            'path' => 'admin/formateurs/{id}',
                            'security_post_denormalize' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                        ],
                    ],
                ],
                'attributes' => [
                    1 => [
                        'security' => 'is_granted(\'ROLE_ADMIN\')',
                        'normalization_context' => [
                            'groups' => [
                                'formateur_read',
                                'formateur_details_read',
                            ],
                        ],
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
13 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
            clone ($p['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
            clone ($p['ApiPlatform\\Core\\Annotation\\ApiFilter'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiFilter')),
        ],
        null,
        [
            'stdClass' => [
                'repositoryClass' => [
                    'App\\Repository\\ProfilRepository',
                ],
                'collectionOperations' => [
                    1 => [
                        'post' => [
                            'security_post_denormalize' => 'is_granted(\'EDIT\', object)',
                            'security_post_denormalize_message' => 'Vous n\'avez pas ce privilege.',
                            'path' => 'admin/profils',
                        ],
                        'get' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas acces a cette ressource.',
                            'path' => 'admin/profils',
                        ],
                    ],
                ],
                'itemOperations' => [
                    1 => [
                        'get' => [
                            'security' => 'is_granted(\'VIEW\',object)',
                            'security_message' => 'Vous n\'avez pas ce privilege.',
                            'path' => 'admin/profils/{id}',
                        ],
                        'delete' => [
                            'security' => 'is_granted(\'EDIT\',object)',
                            'security_message' => 'Vous n\'avez pas ce privilege merci de garder les bonnes informations afin d\'avoir cette possibilité.',
                            'path' => 'admin/profils/{id}',
                        ],
                        'patch' => [
                            'security' => 'is_granted(\'EDIT\',object)',
                            'security_message' => 'Vous n\'avez pas ce privilege.',
                            'path' => 'admin/profils/{id}',
                        ],
                        'put' => [
                            'security_post_denormalize' => 'is_granted(\'EDIT\', object)',
                            'security_post_denormalize_message' => 'Vous n\'avez pas ce privilege.',
                            'path' => 'admin/profils/{id}',
                        ],
                    ],
                ],
                'attributes' => [
                    1 => [
                        'normalization_context' => [
                            'groups' => [
                                'profil_read',
                                'profil_details_read',
                            ],
                        ],
                    ],
                ],
                'filterClass' => [
                    2 => 'ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Filter\\BooleanFilter',
                ],
                'properties' => [
                    2 => [
                        'Statut',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
        ],
        []
    );
},
14 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Id'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Id')),
            clone ($p['Doctrine\\ORM\\Mapping\\GeneratedValue'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\GeneratedValue')),
            clone ($p['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    2 => 'integer',
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    3 => [
                        'profil_details_read',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
            $o[3],
        ],
        []
    );
},
15 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'length' => [
                    255,
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    1 => [
                        'profil_details_read',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
16 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Doctrine\\ORM\\Mapping\\OneToMany'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToMany')),
        ],
        null,
        [
            'stdClass' => [
                'mappedBy' => [
                    'profil',
                ],
                'targetEntity' => [
                    'App\\Entity\\User',
                ],
            ],
        ],
        [
            $o[0],
        ],
        []
    );
},
17 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'boolean',
                ],
                'nullable' => [
                    true,
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    1 => [
                        'profil_read',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
18 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Entity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Entity')),
            clone ($p['Doctrine\\ORM\\Mapping\\InheritanceType'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\InheritanceType')),
            clone ($p['Doctrine\\ORM\\Mapping\\DiscriminatorColumn'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\DiscriminatorColumn')),
            clone ($p['Doctrine\\ORM\\Mapping\\DiscriminatorMap'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\DiscriminatorMap')),
            clone ($p['ApiPlatform\\Core\\Annotation\\ApiResource'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiResource')),
            clone ($p['ApiPlatform\\Core\\Annotation\\ApiFilter'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('ApiPlatform\\Core\\Annotation\\ApiFilter')),
        ],
        null,
        [
            'stdClass' => [
                'repositoryClass' => [
                    'App\\Repository\\UserRepository',
                ],
                'value' => [
                    1 => 'JOINED',
                    3 => [
                        'user' => 'User',
                        'apprenant' => 'Apprenant',
                        'formateur' => 'Formateur',
                        'cm' => 'CM',
                        'admin' => 'ADMIN',
                    ],
                ],
                'name' => [
                    2 => 'type',
                ],
                'type' => [
                    2 => 'string',
                ],
                'collectionOperations' => [
                    4 => [
                        'add_user' => [
                            'method' => 'POST',
                            'path' => '/admin/users',
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas le privilege',
                            'normalization_context' => [
                                'groups' => [
                                    'user_read',
                                ],
                            ],
                        ],
                        'get' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas acces a cette ressource.',
                            'path' => 'admin/users',
                        ],
                    ],
                ],
                'itemOperations' => [
                    4 => [
                        'get' => [
                            'security' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'normalization_context' => [
                                'groups' => [
                                    'user_read',
                                    'user_details_read',
                                ],
                            ],
                            'path' => 'admin/users/{id}',
                            'defaults' => [
                                'id' => null,
                            ],
                        ],
                        'put' => [
                            'security_post_denormalize' => 'is_granted(\'ROLE_ADMIN\')',
                            'security_message' => 'Vous n\'avez pas ces privileges.',
                            'path' => 'admin/users/{id}',
                        ],
                    ],
                ],
                'attributes' => [
                    4 => [
                        'security' => 'is_granted(\'ROLE_ADMIN\')',
                        'normalization_context' => [
                            'groups' => [
                                'user_read',
                                'user_details_read',
                            ],
                        ],
                    ],
                ],
                'filterClass' => [
                    5 => 'ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Filter\\BooleanFilter',
                ],
                'properties' => [
                    5 => [
                        'Archivage',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
            $o[3],
            $o[4],
            $o[5],
        ],
        []
    );
},
19 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Id'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Id')),
            clone ($p['Doctrine\\ORM\\Mapping\\GeneratedValue'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\GeneratedValue')),
            clone ($p['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    2 => 'integer',
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    3 => [
                        'user_read',
                        'profil_read',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
            $o[2],
            $o[3],
        ],
        []
    );
},
20 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ManyToOne'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOne')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'targetEntity' => [
                    'App\\Entity\\Profil',
                ],
                'cascade' => [
                    [
                        'persist',
                    ],
                ],
                'inversedBy' => [
                    'users',
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    1 => [
                        'user_read',
                        'profil_read',
                        'formateur_read',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},
21 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\Column'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\Column')),
            clone ($p['Symfony\\Component\\Serializer\\Annotation\\Groups'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Annotation\\Groups')),
        ],
        null,
        [
            'stdClass' => [
                'type' => [
                    'boolean',
                ],
                'nullable' => [
                    true,
                ],
            ],
            'Symfony\\Component\\Serializer\\Annotation\\Groups' => [
                'groups' => [
                    1 => [
                        'user_read',
                    ],
                ],
            ],
        ],
        [
            $o[0],
            $o[1],
        ],
        []
    );
},

]];
