<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW86o5sD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW86o5sD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW86o5sD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW86o5sD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW86o5sD\App_KernelDevDebugContainer([
    'container.build_hash' => 'W86o5sD',
    'container.build_id' => '0ee46df3',
    'container.build_time' => 1606296116,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW86o5sD');
