<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPUDMlCQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPUDMlCQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPUDMlCQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPUDMlCQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPUDMlCQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PUDMlCQ',
    'container.build_id' => '350a4ff1',
    'container.build_time' => 1606301117,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPUDMlCQ');
