<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWaqcHdV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWaqcHdV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWaqcHdV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWaqcHdV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWaqcHdV\App_KernelDevDebugContainer([
    'container.build_hash' => 'WaqcHdV',
    'container.build_id' => 'dc067cee',
    'container.build_time' => 1606211498,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWaqcHdV');
