<?php

namespace ContainerVp1IQwx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HPoglkxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hPoglkx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hPoglkx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Groupecompetence' => ['privates', 'App\\Repository\\GroupeCompetenceRepository', 'getGroupeCompetenceRepository2Service', true],
        ], [
            'Groupecompetence' => 'App\\Repository\\GroupeCompetenceRepository',
        ]);
    }
}
